competition:
  start:
    position:
      x: -162.53
      y: -95.14
      z: 0.6
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  goal:
    position:
      x: -62.89
      y: -91.49
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
