competition:
  start:
    position:
      x: -62.88
      y: 94.99
      z: 0.0
    orientation:
      x: 0.09
      y: -0.04
      z: -0.89
      w: -0.45
  goal:
    position:
      x: 26.42
      y: 207.57
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
