competition:
  start:
    position:
      x: -62.88
      y: -94.99
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  goal:
    position:
      x: 26.42
      y: -207.57
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
