competition:
  start:
    position:
      x: 335.49
      y: 273.74
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.85
      w: 0.53
  goal:
    position:
      x: 392.47
      y: 249.43
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
