competition:
  start:
    position:
      x: 124.74
      y: -326.97
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.89
      w: -0.45
  goal:
    position:
      x: 259.39
      y: -133.24
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
