competition:
  start:
    position:
      x: 86.76
      y: -6.44
      z: 11.19
    orientation:
      x: 0.09
      y: 0.03
      z: -0.93
      w: -0.34
  goal:
    position:
      x: -6.22
      y: 168.19
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
