competition:
  start:
    position:
      x: -114.78
      y: 35.86
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.98
      w: -0.20
  goal:
    position:
      x: 140.59
      y: 5.37
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
