competition:
  start:
    position:
      x: -7.53
      y: -142.19
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.85
      w: 0.53
  goal:
    position:
      x: 71.53
      y: -302.57
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
