competition:
  start:
    position:
      x: 132.03
      y: -201.17
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.85
      w: 0.53
  goal:
    position:
      x: 151.75
      y: -109.40
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
