competition:
  start:
    position:
      x: 45.24
      y: 225.59
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  goal:
    position:
      x: -3.68
      y: 172.43
      z: 0.0
  traffic_rules: true
  ready_for_ego: false
